/* tslint:disable */
/* eslint-disable */
/**
 * Office Queue API
 * API for the project
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Counter } from './Counter';
import {
    CounterFromJSON,
    CounterFromJSONTyped,
    CounterToJSON,
    CounterToJSONTyped,
} from './Counter';

/**
 * 
 * @export
 * @interface Officer
 */
export interface Officer {
    /**
     * 
     * @type {number}
     * @memberof Officer
     */
    officerCode: number;
    /**
     * 
     * @type {Counter}
     * @memberof Officer
     */
    counter: Counter;
}

/**
 * Check if a given object implements the Officer interface.
 */
export function instanceOfOfficer(value: object): value is Officer {
    if (!('officerCode' in value) || value['officerCode'] === undefined) return false;
    if (!('counter' in value) || value['counter'] === undefined) return false;
    return true;
}

export function OfficerFromJSON(json: any): Officer {
    return OfficerFromJSONTyped(json, false);
}

export function OfficerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Officer {
    if (json == null) {
        return json;
    }
    return {
        
        'officerCode': json['officer_code'],
        'counter': CounterFromJSON(json['counter']),
    };
}

export function OfficerToJSON(json: any): Officer {
    return OfficerToJSONTyped(json, false);
}

export function OfficerToJSONTyped(value?: Officer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'officer_code': value['officerCode'],
        'counter': CounterToJSON(value['counter']),
    };
}

